[package]

name = "playform"
version = "0.0.0"
authors = [
  "Zeke Foppa <benjamin.foppa@gmail.com>",
  "Clark Gaebel <cg.wowus.cg@gmail.com>",
  "Elijah Andrews <elijahcandrews@gmail.com>",
]

[[bin]]
name = "playform"
path = "src/mod.rs"

[features]
default = []
dummy-client = ["dummy-client-lib"]

[dependencies]
clippy = "*"
env_logger= "*"
log = "*"
nanomsg = "*"
thread-scoped = "*"
time = "*"

[dependencies.client-lib]
path = "client/lib"

[dependencies.dummy-client-lib]
path     = "client/dummy"
optional = true

[dependencies.server-lib]
path = "server/lib"

[dependencies.stopwatch]
git = "https://github.com/bfops/stopwatch-rs"
