[package]

name = "playform"
version = "0.0.0"
authors = [
  "Zeke Foppa <benjamin.foppa@gmail.com>",
  "Clark Gaebel <cg.wowus.cg@gmail.com>",
  "Elijah Andrews <elijahcandrews@gmail.com>",
]

[profile.dev]
opt-level = 1           # Controls the --opt-level the compiler builds with
debug = true            # Controls whether the compiler passes -g or `--cfg ndebug`
rpath = false           # Controls whether the compiler passes `-C rpath`
lto = false             # Controls `-C lto` for binaries and staticlibs
debug-assertions = true # Controls whether debug assertions are enabled

[[bin]]
name = "playform"
path = "src/mod.rs"

[dependencies]
clippy = "0.0.58"
env_logger= "*"
log = "*"
nanomsg = "*"
thread-scoped = "*"
time = "*"

[dependencies.client-lib]
path = "client/lib"

[dependencies.server-lib]
path = "server/lib"

[dependencies.stopwatch]
git = "https://github.com/bfops/stopwatch-rs"
