[package]

name = "client"
version = "0.0.0"
authors = [
  "Zeke Foppa <benjamin.foppa@gmail.com>",
  "Clark Gaebel <cg.wowus.cg@gmail.com>",
  "Elijah Andrews <elijahcandrews@gmail.com>",
]

[[bin]]
name = "client"
path = "./mod.rs"

[dependencies]
env_logger= "*"
log = "*"
time = "*"

[dependencies.dummy-client-lib]
path = "../dummy"

[dependencies.stopwatch]
git = "https://github.com/bfops/stopwatch-rs"
