[package]

name = "server"
version = "0.0.0"
authors = [
  "Zeke Foppa <benjamin.foppa@gmail.com>",
  "Clark Gaebel <cg.wowus.cg@gmail.com>",
  "Elijah Andrews <elijahcandrews@gmail.com>",
]

[[bin]]
name = "server"
path = "./mod.rs"

[dependencies]
env_logger    = "*"
log           = "*"
nanomsg       = "*"
thread-scoped = "*"
time          = "*"

[dependencies.server-lib]
path = "../lib"

[dependencies.stopwatch]
git = "https://github.com/bfops/stopwatch-rs"
