[package]

name = "playform-common"
version = "0.0.0"
authors = [
    "Ben Foppa <benjamin.foppa@gmail.com>",
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
    "Elijah Andrews <elijahcandrews@gmail.com>",
  ]

# The development profile, used for `cargo build`
[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false

[lib]
name = "common"
path = "./src/mod.rs"

[dependencies]
log = "*"
rustc-serialize = "*"
time = "*"

[dependencies.cgmath]
git = "https://github.com/bfops/cgmath-rs"

[dependencies.nanomsg]
git = "https://github.com/thehydroimpulse/nanomsg.rs"
